pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone the repository and checkout the specified branch
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/sofibedlu/messaging_app.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                python3 -m venv ${VENV_DIR}
                source ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                source ${VENV_DIR}/bin/activate
                pytest --junitxml=reports/test-results.xml
                '''
                junit 'reports/test-results.xml'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}