apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Replace the values below with base64-encoded strings of your actual credentials.
  mysql-root-password: cm9vdHBhc3N3b3Jk    # "rootpassword" in base64 (example)
  mysql-user: bWVzc2FnaW5nX3VzZXI=           # "messaging_user" in base64 (example)
  mysql-password: bWVzc2FnaW5nX3Bhc3M=         # "messaging_pass" in base64 (example)